# Generated by Django 3.0.4 on 2020-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('applyfor', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('address_name', models.TextField(max_length=200)),
                ('mobile', models.IntegerField(max_length=200)),
                ('phone', models.IntegerField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
